Huge thanks go out to everyone involved in the many pieces of software that I use
to develop this. An incomplete list is:
<ul><li>Ron Velzeboer for <a href="http://templatepower.codocad.com/" target="_blank">TemplatePower</a>,
a really fast and easy to use templating system that forms the basis of PHITE
</li><li>Kristoffer Henriksson for <a href="http://www.ftpedit.com/" target="_blank">FTPEdit</a>
</li><li>R V Libotti for the updated gallery code</li><li>All of my development was done on a laptop running <a href="http://www.phpgeek.com/" target="_blank">PHPTriad</a>;
</li><li>Thanks to <a href="http://www.zope.org/" target="_blank">ZOPE</a> for inspiration. ZOPE is an amazing framework,
way ahead of its time. This is nothing like ZOPE, but if I had never used ZOPE I could never have
conceived of PHITE.
</li><li>Jam Fiala for <a href="http://www.pspad.com/">PSPad</a></li><li>"<a href="http://www.solmetra.com/">SOLMETRA</a>" for the Spaw Editor</li><li>Chris Robson for PHITE itself<br></li></ul>