<!-- Form code created by Web Form Designer 1.2.1 -->
<div id="WFDForm" style="position:relative;left:0px;top:0px;width:360px;height:270px;background-color:#FFFFFF;color:#FF0000;border-width:1;border-style:solid;">
<form name="SendMessage" action="http://www.phite.org.au/tools/mail/formtoemail.php" method="POST" enctype="application/x-www-form-urlencoded">
<input type="submit" name="submitBtn" value="Send" tabindex="1" style="position:absolute;z-index:1;left:59px;top:196px;width:76px;height:23px;">
<input type="reset" name="resetBtn" value="Clear Form" tabindex="2" style="position:absolute;z-index:2;left:225px;top:196px;width:76px;height:23px;">
<input type="text" name="FEdit1" value="" size="40" maxlength="55" tabindex="3" style="position:absolute;z-index:3;left:90px;top:10px;width:261px;height:20px;font-size:10pt;font-family:Arial;font-weight:normal;font-style:normal;color:#000000;background-color:#FFFFFF;">

<div id="WFDObj4" style="position:absolute;z-index:4;left:10px;top:10px;width:78px;height:20px;font-size:10pt;font-family:Arial;font-weight:normal;font-style:normal;text-align:left;color:#000000;">
*Your Name:</div>
<input type="text" name="FEdit2" value="" size="40" maxlength="55" tabindex="4" style="position:absolute;z-index:5;left:133px;top:31px;width:218px;height:20px;font-size:10pt;font-family:Arial;font-weight:normal;font-style:normal;color:#000000;background-color:#FFFFFF;">

<div id="WFDObj6" style="position:absolute;z-index:6;left:10px;top:34px;width:125px;height:20px;font-size:10pt;font-family:Arial;font-weight:normal;font-style:normal;text-align:left;color:#000000;">
*You Email Address:</div>
<div id="WFDObj7" style="position:absolute;z-index:7;left:10px;top:62px;width:57px;height:20px;font-size:10pt;font-family:Arial;font-weight:normal;font-style:normal;text-align:left;color:#000000;">
Message</div>
<textarea  name="Message" rows="6" cols="55" wrap="virtual" tabindex="5" style="position:absolute;z-index:8;left:10px;top:80px;width:342px;height:108px;font-size:10pt;font-family:Arial;font-weight:normal;font-style:normal;color:#000000;background-color:#FFFFFF;">Enter Your Message here</textarea>
<div id="WFDObj9" style="position:absolute;z-index:9;left:15px;top:236px;width:133px;height:18px;font-size:8pt;font-family:Arial;font-weight:normal;font-style:italic;text-align:left;color:#FF0000;">
* indicates a required field</div>
<div id="WFD" style="position:absolute;z-index:10;left:273px;top:253px;font-size:7pt;font-family:Arial;text-align:left;">
<A HREF="http://www.webformdesigner.com">WebFormDesigner</A></div>
</form>
</div>
<!-- End of WebFormDesigner form code -->
