Please let me know what you think of this script, what works and doesn't work
for you, any problems you have and what<br>
you plan to do with the script (if anything).<br>
<br>
If you do use the script it would be great if you could add a link to <a href=
"http://www.phite.org">http://www.phite.org</a><br>
<br>
Send all correspondence to: <a href=
"tombr@phite.org.au">tombr@samsa.com.au</a><br>
<p>
  Thanks! - tom...
</p>
<ul>
  <?php global $PHITE_vars; ?>
  <li>
    <a HREF=<?php print ('"'.$PHITE_vars['PHITE_mainscript'].'?sitesig='.$PHITE_vars['PHITE_sitesig'].'&page=PT_020_Help&subpage=PT_010_FAQ"'); ?>>Frequently asked questions</a>
    <br>
    <br>
  </li>
  <li>
    <a HREF=<?php print ('"'.$PHITE_vars['PHITE_mainscript'].'?sitesig='.$PHITE_vars['PHITE_sitesig'].'&page=PT_020_Help&subpage=PT_020_Known_Issues"'); ?>>Known issues</a>
    <br>
    <br>
  </li>
  <li>
    <a href="http://sourceforge.net/forum/?group_id=46499" target=
    "_blank">Discussion forums</a>
  </li>
</ul>


