PHITE.php is released under the GNU Public License. You are free to use
it under those terms. I would really appreciate feedback on this, both
positive and negative. If you decide to use it, please let me know what
for. If you decide not to then drop me a note saying why it doesn't work for
you. If you have ideas for improvements (or make improvements yourself) let
me know and I will see if they can be added to this distribution. Thanks!