<span style="font-weight: bold;">Content Snipets</span><br><br>PHITE block or element files can contain plain text, HTML or PHP (or a mixture of
all three). Creating these files or 'snippets' is very simple.<p>
<b>Plain Text</b> files will simply have their text inserted in the appropriate element
or block.</p><p>
<b>HTML</b> can also be included, but must not include the &lt;HTML&gt;, &lt;HEAD&gt; or &lt;BODY&gt;
tags -- these will come from the .tpl template file.</p><p>
<b>PHP</b> can also be included, by enclosing the PHP as usual in &lt;?php ... ?&gt; tags.
See the section on PHITE variables for gaining access to the environment.<br></p>