This page includes several sub-pages with examples of PHP code snippets. 

Note that the contents of every snippet is shown below the main body. 

That is very simply done by there being a 'CB' Center Block file in this directory, 
which very simply displays the contents of every file. Note that in this page it 
shows its own code, and in the subpages it shows the example code (through acquisition).

