Here are some examples of sites built using PHITE:
<ul>

<li><a HREF="http://becsonline.com.au/PHITE.php" TARGET="_blank">BECS Online</a><br>
&nbsp;&nbsp;Basa Education and Counselling Services (BECS).<br>

<li><a HREF="http://multiword.sourceforge.net/" TARGET="_blank">SIGLEX-MWE</a><br>
&nbsp;&nbsp;The multiword expressions community website became the SIGLEX-MWE website!.

<li><a HREF="http://codex.pk.be/" TARGET="_blank">Codex Studiosorum Bruxellensis</a><br>



</ul>