<center><h3>Quick Start</h3></center>
<ul><li>You need to be running PHP 4 (tested on 4.0.6 only so far);
</li><li>You need Ron Velzeboer's excelent TemplatePower 2.0 or higher. 2.0 beta is included with
this distribution. Please check <a href="http://templatepower.codocad.com/" target="_blank">Ron's site</a> for
newer versions and documentation;
</li><li>Download and unpack the demo package;
</li><li>Modify $siteroot in the main script file PHITE.php to be the full URL to the directory PHITE.php is in;
</li><li>FTP files to your server, maintaining directory structure (.php, .tpl and .inc files should be transfered in 'text' mode);
</li><li>Point your browser to PHITE.php, you should see the demo site;
</li><li>Explore file structure, try modifying files and templates.
</li></ul><span style="font-weight: bold;">Spaw Editor</span><br><ul><li>Install the Spaw editor (included in the download)<br></li><li>change the spaw_control.config.php to suit your site</li><li>Explore and edit your site.<br></li></ul>