<a HREF="http://www.php.net" TARGET="_blank">PHP</a><br>
<a HREF="http://templatepower.codocad.com/" TARGET="_blank">TemplatePower</a><br>
<a HREF="http://www.zope.org" TARGET="_blank">ZOPE</a><br>
<a HREF="http://www.hotscripts.com/PHP/" TARGET="_blank">HotScripts</a><br>
<a HREF="http://www.scriptsearch.com/PHP/" TARGET="_blank">ScriptSearch</a>
<p><center>
<A href="http://sourceforge.net/projects/phite/" TARGET="_blank"> <IMG src="http://sourceforge.net/sflogo.php?group_id=46499&type=1" width="88" height="31" border="0" alt="SourceForge Logo">
<br>PHITE is now listed on Sourceforge.net</A></center>